//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogParserAndTransfer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class AppSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSetting defaultInstance = ((AppSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSetting())));
        
        public static AppSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.00:00:00")]
        public global::System.TimeSpan YoungEnoughTimeSpan {
            get {
                return ((global::System.TimeSpan)(this["YoungEnoughTimeSpan"]));
            }
            set {
                this["YoungEnoughTimeSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ScannedInfo.json")]
        public string ScanInfoFile {
            get {
                return ((string)(this["ScanInfoFile"]));
            }
            set {
                this["ScanInfoFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestCam")]
        public string TestPlatform {
            get {
                return ((string)(this["TestPlatform"]));
            }
            set {
                this["TestPlatform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int TestCamSNLen {
            get {
                return ((int)(this["TestCamSNLen"]));
            }
            set {
                this["TestCamSNLen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int KineticSNLen {
            get {
                return ((int)(this["KineticSNLen"]));
            }
            set {
                this["KineticSNLen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Crola\\")]
        public string OutputFolder {
            get {
                return ((string)(this["OutputFolder"]));
            }
            set {
                this["OutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.csv")]
        public string ScanFileType {
            get {
                return ((string)(this["ScanFileType"]));
            }
            set {
                this["ScanFileType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_copy,SNForLogService,AUTO_CLEAN,Testcam_automation")]
        public string ExcludeFileName {
            get {
                return ((string)(this["ExcludeFileName"]));
            }
            set {
                this["ExcludeFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsGetSNColumnNameFromJson {
            get {
                return ((bool)(this["IsGetSNColumnNameFromJson"]));
            }
            set {
                this["IsGetSNColumnNameFromJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsGetTestTimeFromAccessaryFile {
            get {
                return ((bool)(this["IsGetTestTimeFromAccessaryFile"]));
            }
            set {
                this["IsGetTestTimeFromAccessaryFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\tstplan,C:\\\\CSV_LOG")]
        public string Bak {
            get {
                return ((string)(this["Bak"]));
            }
            set {
                this["Bak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aws41eispprod.cluster-cbdfio6hbo5q.rds.cn-north-1.amazonaws.com.cn")]
        public string DBServerIP1 {
            get {
                return ((string)(this["DBServerIP1"]));
            }
            set {
                this["DBServerIP1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string DBServerPort1 {
            get {
                return ((string)(this["DBServerPort1"]));
            }
            set {
                this["DBServerPort1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("suzhoueis")]
        public string DBAccount1 {
            get {
                return ((string)(this["DBAccount1"]));
            }
            set {
                this["DBAccount1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aws41eisdbprod1.cbdfio6hbo5q.rds.cn-north-1.amazonaws.com.cn")]
        public string DBServerIP {
            get {
                return ((string)(this["DBServerIP"]));
            }
            set {
                this["DBServerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("suzhoueis")]
        public string suzhoueis {
            get {
                return ((string)(this["suzhoueis"]));
            }
            set {
                this["suzhoueis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string DBServerPort {
            get {
                return ((string)(this["DBServerPort"]));
            }
            set {
                this["DBServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SuzHouE!$")]
        public string DBPassword {
            get {
                return ((string)(this["DBPassword"]));
            }
            set {
                this["DBPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SuzHouE!$")]
        public string DBPassword1 {
            get {
                return ((string)(this["DBPassword1"]));
            }
            set {
                this["DBPassword1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("suzhoueis")]
        public string Logitech1 {
            get {
                return ((string)(this["Logitech1"]));
            }
            set {
                this["Logitech1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("suzhoueis2")]
        public string DBAccount {
            get {
                return ((string)(this["DBAccount"]));
            }
            set {
                this["DBAccount"] = value;
            }
        }
    }
}
