using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FileHelpers;

namespace LogParserAndTransfer
{
    [DelimitedRecord(",")]
    [IgnoreEmptyLines()]
    //[IgnoreFirst()]
    public class TestCamLog
    {
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string SNo { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Status { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Comment { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string EID { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string ErrCode { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Time { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Station { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string SerialNumber { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string BOMVersion { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Totalsecs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Failures { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Plugin { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Plugin_current { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Enum_current { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string DevInfo_FW { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string DevInfo_register_44130 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string DevInfo_current { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string DevInfo_speed { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string DevInfo_VID { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string DevInfo_PID { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_AVG_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_AVG_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_AVG_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_L { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_a { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_b { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_dE { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_dL { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_SNR_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_SNR_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_SNR_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_AVG_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_AVG_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_AVG_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_L { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_a { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_b { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_dE { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_dL { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_SNR_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_SNR_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_SNR_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_AVG_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_AVG_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_AVG_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_L { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_a { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_b { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_dE { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_dL { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_SNR_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_SNR_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_SNR_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_AVG_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_AVG_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_AVG_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_L { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_a { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_b { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_dE { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_dL { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_SNR_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_SNR_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_SNR_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_AVG_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_AVG_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_AVG_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_L { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_a { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_b { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_dE { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_dL { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_SNR_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_SNR_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_SNR_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_AVG_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_AVG_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_AVG_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_L { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_a { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_b { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_dE { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_dL { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_SNR_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_SNR_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_SNR_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_AVG_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_AVG_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_AVG_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_L { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_a { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_b { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_dE { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_dL { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_SNR_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_SNR_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_SNR_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_AVG_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_AVG_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_AVG_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_L { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_a { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_b { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_dE { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_dL { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_SNR_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_SNR_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_SNR_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_AVG_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_AVG_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_AVG_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_L { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_a { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_b { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_dE { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_dL { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_SNR_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_SNR_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_SNR_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_AVG_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_AVG_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_AVG_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_L { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_a { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_b { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_dE { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_dL { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_SNR_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_SNR_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_SNR_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_AVG_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_AVG_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_AVG_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_L { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_a { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_b { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_dE { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_dL { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_SNR_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_SNR_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_SNR_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_AVG_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_AVG_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_AVG_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_L { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_a { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_b { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_dE { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_dL { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_SNR_R { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_SNR_G { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_SNR_B { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Left_up__x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Left_up__y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Left_up__MTF { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Rigth_up_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Rigth_up_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Rigth_up_MTF { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Left_dn__x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Left_dn__y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Left_dn__MTF { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Right_dn_x1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Right_dn_y1 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Right_dn_MTF { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend_current { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string VCM_pos { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string VCM_mtf { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string VCM_mA { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string reEnum_current { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_R_AC { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_R_DC { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_R_THD { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_R_AC2 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_R_DC2 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_R_THD2 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_L_AC { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_L_DC { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_L_THD { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_L_AC2 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_L_DC2 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_L_THD2 { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Enum_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string DevInfo_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string video_inc_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string White_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray8_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray6_5_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray5_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Gray3_5_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Black_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Blue_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Green_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Red_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Yellow_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Magenta_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Cyan_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Left_up__secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Rigth_up_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Left_dn__secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Right_dn_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Preview_inc_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string VCM_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string reEnum_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Preview_des_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_R_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string chan_L_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Preview_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Audio1_secs { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend1_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend2_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend3_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend4_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend5_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend6_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend7_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend8_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend9_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend10_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend11_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend12_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend13_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend14_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend15_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend16_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend17_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend18_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend19_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend20_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend21_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend22_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend23_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend24_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend25_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend26_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend27_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend28_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend29_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend30_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend31_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend32_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend33_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend34_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend35_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend36_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend37_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend38_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend39_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend40_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend41_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend42_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend43_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend44_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend45_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend46_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend47_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend48_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend49_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend50_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend51_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend52_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend53_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend54_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend55_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend56_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend57_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend58_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend59_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend60_curr { get; set; }

        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend61_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend62_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend63_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend64_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend65_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend66_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend67_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend68_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend69_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend70_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend71_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend72_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend73_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend74_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend75_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend76_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend77_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend78_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend79_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend80_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend81_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend82_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend83_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend84_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend85_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend86_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend87_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend88_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend89_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend90_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend91_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend92_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend93_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend94_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend95_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend96_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend97_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend98_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend99_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend100_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend101_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend102_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend103_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend104_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend105_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend106_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend107_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend108_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend109_curr { get; set; }
        [FieldOptional] [FieldNullValue(typeof(string), "")] public string Suspend110_curr { get; set; }

    }
}
